### ISSUE TITLE
gh-pages

### ISSUE THREAD

**Issue by ackoujens** [RachelJMorris/Stacy-and-Mari-Dressup#1]
Was browsing around and saw you were working on this HTML5 game.
Wanted to give you the tip of maybe pushing it to a gh-pages branch. Enabling you to actually showcase your html games.

**Comment by RachelJMorris** [comment]
I could, but it is also available on itch.io here:

https://moosader.itch.io/stacy-mari-dress-up

**Comment by ackoujens** [comment]
Alright. Was just a suggestion. ^^
